// import 'package:flutter/material.dart';
import './task_model.dart';

List<Task> taskList = [
  Task(
    id: '1',
    title: 'Task',
    description: 'Description of my task 1',
    date: DateTime.now(),
    time: '7:30am',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '2',
    title: 'Task',
    description: 'Description of my task 2',
    date: DateTime.now(),
    time: '7:00pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '3',
    title: 'Task',
    description: 'Description of my task 3',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '4',
    title: 'Task',
    description: 'Description of my task 4',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '5',
    title: 'Task',
    description: 'Description of my task 5',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '6',
    title: 'Task',
    description: 'Description of my task 6',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '7',
    title: 'Task',
    description: 'Description of my task 6',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '8',
    title: 'Task',
    description: 'Description of my task 6',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
  Task(
    id: '9',
    title: 'Task',
    description: 'Description of my task 6',
    date: DateTime.now(),
    time: '7:30pm',
    createdDate: DateTime.now(),
  ),
];
